# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  id: "CloudflareScanner"
  binary: "CloudflareScanner"
  goos:
    - darwin
    - freebsd
    - linux
    - windows
  goarch:
    - 386
    - amd64
    - arm
  #hooks:
    #post: ./compile.bat "{{ dir .Path }}"
archives:
- replacements:
    darwin: MacOS
    linux: Linux
    windows: Windows
    386: x86
    amd64: x64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "v1.1.0"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'